### ISSUE TITLE
[9장] 단위 테스트 

### ISSUE THREAD

**Issue by aronalee** [aronalee/swm_14_div_study#10]

**Comment by aronalee** [comment]
# 요약

> 테스트 코드를 작성하는 전반적인 팁들.

- 그릇된 정보는 피해라
- 프로그램이 돌아가는 환경과 테스트 환경은 다르기에 실제 프로그램에서 돌아가지 못하는 방법으로 테스트를 할 수 있다.
- assertions는 개념당 1개를 유지해라
- 테스트 코드는 개념당 1개를 유지해야 한다
- first principle
   - Fast: 테스트 코드는 빨라야 한다
   - Independent: 테스트 코드들은 독립적이어야 한다
   - Repeatable: 테스트 코드는 원본 코드가 바뀌지 않는한 언제든 동일한 결과가 나와야 한다
   - Self-Validation: 테스트 코드 결과의 검증은 개발자가 아닌 테스트코드 스스로 해야한다
   - Timely: 테스트 코드는 적시에 작성되어야 한다
- given/when을 @Before 함수에 넣으면 이 코드가 하나의 템플릿이 되기에 테스트 코드에는 then 부분만 들어가도록 만들 수 있다.
   -  이 방법은 모든 코드가 동일한 given/when을 가지는 문제점이 가진다.

---

# 내 생각

예전에 테스트코드 작성할려고 시도했다가 고생했던 경험들과 과거의 잘못들에 대해 이해하고 반성하게 되었던 챕터였다.

assertion의 개수를 1개로 줄이라는 것은 최대한 지키려고 했던 규칙이었다. 이 규칙을 위해 어떻게는 assertion을 1개를 유지하기 위해 assertions라이브러리와 스택오버플로우를 뒤져본 경험이 있다. 이렇게 고생해서 만든 테스트 코드는 정작 읽기가 어려웠다. assertions는 1개만 쓰라는 규칙을 준수하였음에도 불구하고 읽기가 어려워서 '내가 잘못하고 있는건가' 라는 생각을 하였다. 이 책에서 테스트 코드에는 1개의 것을 테스트를 하는 것을 보니 '아, 내가 개념당 1개가 아니라 무조건 assertions를 1개만 가지도록 만들려고 억지로 합쳤기에 읽기가 어려웠구나' 라는 사실을 깨달았다.

first 원칙은 이 원칙이 깨진 상태로 테스트 코드를 써본 경험이 있어서 원칙의 중요성을 잘 알고 있다. Repeatable하지 않아 테스트 코드가 돌릴 때마다 성공, 실패가 반복되어 테스트 결과를 등한시해본 경험도 있고 self-validation을 지키지 못해 테스트 코드를 눈으로 검증하다 귀찮아져서 안보게 되었던 경험도 있다. 몸으로 느꼈다보니 저 규칙들에 대한 중요성을 백번 강조하고 싶다.

**Comment by Roddyd94** [comment]
## 목적
유연성, 유지보수성, 재사용성 제공
실제 코드를 유연하게 만드는 버팀목 -> 단위 테스트

## 방법
TDD 법칙
- 실패하는 단위 테스트를 작성할 때 까지 실제 코드를 작성하지 않는다.
- 컴파일은 실패하지 않으면서 실행이 실패하는 정도로만 단위 테스트를 작성한다.
- 현재 실패하는 테스트를 통과할 정도로만 실제 코드를 작성한다.

BUILD-OPERATE-CHECK
- 테스트 자료 생성
- 테스트 자료 조작
- 조작한 결과 확인

DSL로 테스트 코드 구현

테스트용 표준
- 실제 환경에서는 사용하지 않음

테스트 당 assert 하나
- 테스트에 대한 결론이 하나
- 맥락에 따라 사용 권고

given-when-then 관례
- template method 패턴 사용
- 독자적인 테스트 클래스 생성
  - @Before 함수에 given/when
  - @Test 함수에 then

## 요약
개념 당 assert 문 수를 최소로 줄여라
테스트 함수 하나는 개념 하나만 테스트하라
FIRST : 빠르고, 독립적으로, 반복가능하게, 자가검증하는, 적시에

## 생각
단위 테스트가 아직 익숙하지 않아 TDD 법칙부터 이해하지 못했다.
테스트에 관한 책을 먼저 읽어야 할 듯

**Comment by chj990707** [comment]
실패하는 단위 테스트를 작성할 때까지 실제 코드를 작성하지 않는다.
컴파일은 실패하지 않으면서 실행이 실패하는 정도로만 단위 테스트를 작성한다.
현재 실패하는 테스트를 통과할 정도로만 실제 코드를 작성한다.

테스트 코드도 깨끗하게 유지해야 한다
테스트당 개념은 하나로 유지한다
빠르게, 독립적으로, 반복 가능하게, 자가검증하는, 적시에

### 생각
테스트코드도 코드이니만큼 깨끗하게 유지해야만 개발이 효율적이라는 말은 당연할 것이다. 그러나 테스트 코드를 짜 본 적이 없어서 이번 장을 직접 적용하는 데는 많은 연습이 필요할 것 같다.
