### ISSUE TITLE
[11장] 시스템

### ISSUE THREAD

**Issue by aronalee** [aronalee/swm_14_div_study#12]

**Comment by chj990707** [comment]
* 시스템 제작과 사용을 분리하라: 지연된 초기화가 문제를 유발할 수 있다.
* Main을 분리하라: 객체를 생성하는 코드는 모두 main에 넣고, 나머지 시스템은 객체 생성과 연결이 끝났다고 가정한다.
* 의존성 주입
* 횡단 관심사: 영속성 같이 객체 경계를 넘나드는 개념을 프레임워크에 위임한다.
* 시스템 구조는 모듈화된 영역으로 구성되어, 서로 다른 영역의 영향을 최소화하고 테스트 주도 기법을 사용할 수 있도록 한다.

### 생각
개별적인 코드가 깨끗해도 한데 묶는 시스템이 깨끗하지 못하면 쓸모가 없다.의존성 주입은 마인크래프트 모드 개발 중에 접한 적이 있는 개념이었는데, 클래스의 부모 의존성을 변경할 수 있었기 때문에 클린 코드를 만드는 방법으로 소개된 것은 다소 의외였다.

**Comment by aronalee** [comment]
# 요약

- 소프트웨어 시스템은 준비과정과 런타임의 로직을 분리해야 한다
- IoC는 한 객체가 맡은 보조 책임을 떠넘겨서 새로운 객체에게 책임을 넘긴다.
- cross-cutting: 같은 관심사를 가진 기능은 하나의 프레임워크에 위임

---

# 생각

마침 Spring AOP를 배우고 있어서 cross-cutting을 흥미롭게 봤다. 그리고 관심사를 분리할 수 있는 방법이 Spring AOP뿐만 아니라 다른 것도 배울 수 있었다. 자바 프록시를 보다 Spring AOP 코드를 보니 Spring AOP가 얼마나 많은 코드를 줄여주는지를 볼 수 있었다.
