### ISSUE TITLE
[GoF] Singleton Pattern

### ISSUE THREAD

**Issue by aronalee** [aronalee/swm_14_div_study#16]

**Comment by aronalee** [comment]
# 요약

- 인스턴스를 1개만 유지시켜 여러 객체가 동일한 1개의 인스턴스를 접근시키도록 하는 패턴
- 멀티 스레드 환경에서는 여러 스레드가 단일 스레드에 접근하는 방법에 대한 고민이 필요함

---

# 사용처

- 게임 설정 정보: 게임이라는 내용이 진행되는 동안 오직 1개의 설정정보만 가지고 있고 이 정보가 여러개의 객체를 사용
- spring dispatcherservlet: SpringMVC에서 Servlet Container 이며 어느 Controller가 요청을 처리할 지를 결정해서 Controller에게 처리를 위임하는 servlet.

**Comment by aronalee** [comment]
# 요약

- 인스턴스를 1개만 유지시켜 여러 객체가 동일한 1개의 인스턴스를 접근시키도록 하는 패턴
- 멀티 스레드 환경에서는 여러 스레드가 단일 스레드에 접근하는 방법에 대한 고민이 필요함

---

# 사용처

- spring dispatcherservlet: SpringMVC에서 Servlet Container 이며 어느 Controller가 요청을 처리할 지를 결정해서 Controller에게 처리를 위임하는 servlet.

**Comment by chj990707** [comment]
* 클래스의 인스턴스를 하나만 유지해 이 클래스에 대한 참조가 모두 하나의 인스턴스를 참조하게 하는 방법
* 클래스의 생성자 접근자를 제한하고, 공개된 정적 객체 하나를 유지하는 구현 방법이 있음
## 사용처
logger 클래스
전역 변수 클래스(프로그램 세팅 등)
