### ISSUE TITLE
[GoF] State Pattern

### ISSUE THREAD

**Issue by aronalee** [aronalee/swm_14_div_study#17]

**Comment by aronalee** [comment]
# 요약

- 상태를 객체화를 하여 상태에 따라 행동을 polyglot하는 pattern
- 새로운 상태를 추가할 때 기존의 상태에 영향을 주지 않아 유리
- strategy pattern과의 차이
   - strategy pattern: 행동하는 알고리즘을 클래스로 만들어 행동 하는 방식을 여러개로 제시
   - state pattern: 상태를 클래스로 만들고 클래스 내에 행동을 넣어 상태에 따른 행동 방식을 제시

---

# 사용처

state pattern에는 게임쪽에서 사용처를 찾을 수 있었다. state pattern은 캐릭터가 상태에 따른 움직임을 다르게 만들 수 있다. 캐릭터가 물속에 있으면 수영 모션을 취하거나 땅에 있으면 걷기 모션을 취하는 방식으로 만들어서 같은 행동을 하더라도 상태나 환경에 따라 다르게 움직일 수 있다

**Comment by chj990707** [comment]
* 소프트웨어의 동작에 관련된 패턴
* 프로그램의 행동 상태를 객체로 만듦
* 상태 클래스를 새로 추가하는 것으로 기존 상태와 동작 클래스에 변화 없이 행동 패턴을 추가 가능
### 사용처
게임에서 인공지능의 행동 패턴이 상황에 따라 변하는 등의 상황에서 많이 쓰인다. 예를 들어 체력이 적어지면 도망치고, 충분히 회복한 후 다시 적을 공격하는 등의 패턴을 구현할 수 있다.
