### ISSUE TITLE
[GoF] Command Pattern

### ISSUE THREAD

**Issue by aronalee** [aronalee/swm_14_div_study#19]

**Comment by aronalee** [comment]
## 요약

- 객체의 행위를 추상화하는 패턴
- Command가 행위를 추상화하고 Command를 상속받는 객체에게 행동을 위임
- 클라이언트에게 호출받아 처리하는 객체가 Command를 바라보고 있지만 구현체에 따라 Command로 실행할 기능들을 다르게 만듬

---

## 사용처

- java의 Runnable(java.lang.runnable): runnable은 java에서 thread를 만들어 실행하는 코드이다. 이 코드가 Command인 이유는 Runnable은 `run()` 이라는 thread내에서 실행할 작업을 분리하여 thread가 실행할 작업을 Runnable 인터페이스로 추상화를 시켰다.

**Comment by chj990707** [comment]
* 행위 패턴
* 객체가 해야 할 행동을 command 객체로 추상화
* 기능의 실행자와 호출자 사이의 의존성을 제거함
* 기록 혹은 명령의 취소가 가능해짐

### 사용처
* 게임에서 행동을 취소하고 이전으로 되돌리는 기능
