### ISSUE TITLE
[클린코드] 1장: 깨끗한 코드

### ISSUE THREAD

**Issue by aronalee** [aronalee/swm_14_div_study#2]

**Comment by aronalee** [comment]
# 1장 정리

- 클린코드는 책을 찾아서 보기보단 클린 코드를 만드는 습관을 만드는 것이 중요하다.
- 좋은 코드를 만드는 습관은 기술적 부채를 막을 수 있는 좋은 습관이다.
- 개발자들은 프로그램을 만드는 과정 중 대부분의 시간을 코드를 읽는데 사용한다. 즉 읽기 좋은 코드만 읽어도 개발시간을 단축할 수 있다.


# 생각

클린코드라는 책의 목적은 이 내용을 달달외워라가 아닌 클린코드를 만드는 습관을 만들기 위해 계속 연습을 해보라는 것이 이 책을 관통하는 내용으로 보인다. 한번 읽어보고 내용을 이해하고 넘어가기 보단 한번이라도 써보고 클린코드를 느껴보는게 어떤가 싶다.

**Comment by Roddyd94** [comment]
## 필요성
코드를 쓰는 시간보다 읽는 시간이 더 많다.
나쁜 코드는 번식하며 팀 생산성을 떨어뜨린다.

## 깨끗한 코드
단순하며 명백하고 한 가지 일을 한다.
의미 있는 이름을 사용하며 읽기 쉽다.
의존성과 중복을 최소화한다.

## 생각
언어는 시대를 반영하고, 사회를 반영한다.
문화는 언어로 표현되며, 쌓이고 변한다.

클린 코드는 개발자들의 문화다.
이 책은 객체지향 시대를 살아온 객체지향 개발자들의 의견을 담고 있다.
객체지향의 언어로 표현된 클린 코드도 쌓이고 변할 것이다.
그러면 미래에 클린 코드는 어떤 부분이 전승되고, 어떤 부분이 변할까?

**Comment by chj990707** [comment]
## 나쁜 코드
나쁜 코드는 개발 프로세스 전체를 비효율적으로 만든다.
프로그래머는 코드를 깨끗하게 유지할 의무가 있다.

## 깨끗한 코드
의존성과 중복을 최소한으로 한다.
한 가지 일을 제대로 처리한다.
이름을 명쾌하게 짓는다.
코드의 의도가 확실히 드러나야 한다.
고치기 쉬워야 한다.
코드는 읽기 쉬워야 한다. 코드를 짤 때 읽는 시간이 쓰는 시간보다 10배 이상 길기 때문이다.
체크아웃할 때보다 더 깨끗한 코드를 체크인하라.

## 생각
저자는 클린 코드를 자전거와 같다고 말한다. 한 번 보고 바로 익힐 수 있는 기술이 아니라 계속 연습해야만 익힐 수 있는 기술이라는 뜻에서 말이다. 이 책을 읽는 데서 그치지 않고 오랫동안 실습을 해야만 좋은 코드를 쓸 수 있을 것이다.

**Comment by aronalee** [comment]
1장 스터디 종료
