### ISSUE TITLE
[GoF] Observer pattern

### ISSUE THREAD

**Issue by aronalee** [aronalee/swm_14_div_study#20]

**Comment by aronalee** [comment]
## 요약

- 객체 행위 패턴
- observer 객체: subject 객체를 감시
- subject객체: observer에게 감시당하는 객체
- observer가 subject의 상태를 감시하며 상태가 변경이 될 때마다 감지하는 패턴
- 객체의 변경 사항을 실시간으로 전파가 가능함

---

## 사용처

- event-driven-programming: 이벤트가 발행되면 리스너가 이를 받아 처리가능한 객체에게 전달.

### observer vs pub/sub

두 패턴 모두 event-driven-programming 에서 사용하나 다음의 차이가 있다.

- observer
```
observer -> subject 
observer <- subject
```
   - 동기방식으로 구성
   - observer는 감시하고 있는 subject를 알고 있어야 함 => observer와 subject간의 결합이 높다.
- pub/sub
```
pub -> broker 
broker <- subject
broker -> subject
```
   -  비동기 방식으로 구성
   - event channel 로 이벤트를 송수신
   - publisher, subscriber모두 message broker만 바라보고 서로를 알 필요가 없다 => 결합도가 낮다
   - publisher가 message broker에 이벤트를 전달하고 subscriber가 broker에게 이벤트를 받아서 처리함

**Comment by chj990707** [comment]
* 행위 패턴
* 관찰 대상이 되는 객체에 옵저버(리스너)를 등록함
* 변화가 발생할 시 관찰대상이 등록된 옵저버에 상황 전파

### 사용처
* 이벤트 기반 프로그래밍: 사용자 입력에 대한 즉각적인 반응 전파 등
