### ISSUE TITLE
[GoF] Visitor pattern

### ISSUE THREAD

**Issue by aronalee** [aronalee/swm_14_div_study#21]

**Comment by chj990707** [comment]
* 데이터 구조와 행위자를 구분하는 패턴
* 개방-폐쇄 원칙을 구현하는 방법
* 데이터 구조 클래스의 다형성을 보장하기 위해 accept 메소드를 추가해 더블 디스패치로 해결함
* 단점: 데이터 구조를 추가할 때마다 모든 비지터를 수정해야 함
### 사용례
여러 개의 객체를 파일로 내보내기

**Comment by aronalee** [comment]
# 요약

- Vistior: 로직을 가진 객체. element에 방문해서 Visitor가 담당하는 로직을 처리
- Element: Visitor가 방문하여 로직을 처리해야하는 공간
- Visitor에게 일부 동작의 책임을 위임해서 처리
- Visitor가 담당하는 로직을 추상화를 하여 처리가 가능
- Visitor의 요청, 반환 타입이 정해짐

---

# 사용례

- FileVisitor: 파일을 순회하는 방식을 정의. Visitor 객체로서 파일을 순회하는 방식을 직접 정의가 가능
