### ISSUE TITLE
[GoF] Strategy pattern

### ISSUE THREAD

**Issue by aronalee** [aronalee/swm_14_div_study#22]

**Comment by chj990707** [comment]
* 개방-폐쇄 원칙을 구현하는 패턴
* 원래 클래스(콘텍스트)에서 알고리즘을 전략 클래스로 분리해 구현
* 동일한 계열의 알고리즘들을 묶는 하나의 추상 전략 클래스를 정의
* 알고리즘이 많고, 경우에 따라 서로 바꿔 써야 할 때 유효한 패턴
### 사용례
* 이동 수단에 따른 길 찾기 알고리즘 변화
* 게임에서 사용하는 무기에 따른 공격 패턴 변화

**Comment by aronalee** [comment]
# 요약

- 동작하는 알고리즘(전략)을 추상화하는 패턴
- 문제를 푸는 여러 알고리즘이 있을 때 유리

---

# 사용처

- java의 compareTo를 이용한 정렬(Comparator) : 정렬하는 기준을 추상화하여 어떻게 정렬을 할 것인지를 정의
