### ISSUE TITLE
[GoF] Decorator

### ISSUE THREAD

**Issue by aronalee** [aronalee/swm_14_div_study#23]

**Comment by chj990707** [comment]
* 객체의 기본 기능에 추가할 수 있는 기능을 데코레이터 객체로 분리함
* 컴포넌트 객체를 감싸는 새로운 데코레이터 객체를 생성
* 데코레이터와 컴포넌트는 같은 인터페이스를 상속하도록 함
* 기능이 비슷한 오브젝트가 많이 생기는 것을 유의해야 함
## 용례
* 스크롤, 크기, 외곽선 등의 속성을 선택적으로 사용하는 웹브라우저 컴포넌트

**Comment by aronalee** [comment]
# 요약

- 객체의 기능을 추상화하는 패턴
- 기본 객체가 존재하며 부가 기능을 Wrapping하는 패턴
- 새로운 기능의 조합이 용이합
- 기능이 많아질 수록 이를 조합해서 사용하기 어려움

---

# 용례

- Collections 객체
   -  Collection 객체를 수정하지 않고 새로운 기능을 추가가 가능
   -  `checkedList(collection, class)` : collection에 들어갈 객체 타입을 `class`로 강제로 지정
- 알림 서비스
   -  알림을 처리하는 방식을 고정하고 보내는 방식(이메일, 문자 등)을 decorator를 이용해 여러개로 추상화
