### ISSUE TITLE
[GoF] Facade pattern

### ISSUE THREAD

**Issue by aronalee** [aronalee/swm_14_div_study#24]

**Comment by chj990707** [comment]
* 여러 개의 저수준 객체들을 묶어 하나의 인터페이스로 외부에 전달하는 방법
* 데코레이터는 하나의 객체를 데코레이터로 감싸는 것을 반복, 파사드는 하나의 파사드가 여러 개의 객체를 감쌈
* 최대한 같은 게층의 객체들끼리 묶어서 파사드를 설계하도록 해야 함
## 용례
* 게임에서 스킬을 사용했을 때 여러 개의 효과를 같이 처리해주는 핸들러 객체

**Comment by aronalee** [comment]
# 요약

- Facade: 건물의 정면
- 건물의 전체는 크지만 정면만 본다 => 전체 기능이 아닌 일부 기능만 필요할 때 사용한 패턴
- 전체 기능을 모두 노출시키자니 서비스 결합도가 너부 크고, 그렇다고 노출을 안시키자니 기능을 사용하기 어려울 때  사용
- 비슷한 기능을 하는 객체를 같은 계층으로 보고 이를 하나의 facade로 추상화
- 상호 작용의  결합도를 낮추는 패턴
- facade vs adapter
   - adapter: 클라이언트가 사용하는 구현체 변경을 용이
   - facade: 객체와 시스템간의 결합도를 낮추기 위함
---

# 용례

- repository 계층: sql을 이용하다가 nosql을 사용할 경우 데이터를 처리하는 스크립트가 완전히 달라지지만 객체를 조회하는 방법을
