### ISSUE TITLE
[2장] 의미있는 이름

### ISSUE THREAD

**Issue by aronalee** [aronalee/swm_14_div_study#3]

**Comment by aronalee** [comment]
# 요약

> 소제목들을 묶음

- 이름은 명확해야 한다.
   - 의도를 분명히 밝혀라: d, a, b같은 의미를 모르는 내용보단 적어도 의미를 나타내는 이름으로 지어라
   - 그릇된 정보는 피해라: 약어사용을 주의해라. 책에서의 hp예제보니 hp컴퓨터가 먼저 떠올랐다.
   - 의미있게 분류해라: 본인이 아닌 코드를 읽는 사람이 차이를 알도록 분류해라
- 프로그래밍은 사회 활동이다.
   - 발음하기 쉬운 이름을 사용해라: 이름의 축약은 발음하기 어려워져 소통에 장애 요인이다.
   - 검색하기 쉬운 이름을 사용해라: 가독성이 높아지고 유지보수가 용이해진다
   - 인코딩을 피해라: 타입을 이름에 명시하는 것은 요즘처럼 프로그래밍 환경이 좋은 곳에서는 오도의 가능성이 있으므로 지양해라.
- 명료함이 최고이다.
   - 자신의 기억력을 자랑하지 말아라: 이름을 대충 짓고 기억하고 넘어가기 보단 최대한 의미를 표현해라.
   - 기발한 이름은 피해라: 서비스에 관련없는 특정 문화에서만 사용하는 이름은 다른 개발자가 의도를 찾기 어렵다.
   - 한 개념에 한 단어를 사용해라: 일관성 있는 어휘 코드를 사용해라
   - 말장난을 하지 말아라: 대충 훓어봐도 이해할 코드 작성하여야 한다.
   - 해법 영역에서 가져온 이름을 사용해라: 도메인을 이용해 모든 이름을 쉽게 지으려는 것은 잘못된 생각이다.
   - 문제 영역에서 가져온 이름을 사용해라: 동료 개발자도 같은 개발자이다. 개발자들끼리 아는 용어를 이름에 쓰는 것은 잘못된 행위가 아니다.
   - 의미있는 맥락을 추가해라: 이름을 쓰는 곳은 반드시 의미가 있다(단순 루프 제외).
   - 불필요항 맥락을 없애라: 의미가 분명하면 내용은 생략해 이름의 길이를 줄여라.
---

# 내 생각

프로그래밍 중에 가장 어려웠던 것은 이름짓기 였다. 코테, 서비스 개발을 할 때 '이 변수/메소드/클래스 는 어떤 이름을 지어야 이름을 제공할 수 있을까'를 고민하였다.
이름을 지을 때 '난 어떻게 지었더라' 를 생각하면서 읽으니 과거의 잘못들이 보여서 책을 읽으며 '아 내가 이런 생각을 해서 잘못된 이름이 나왔구나'를 생각할 수 있는 시간이 되었다.

**Comment by chj990707** [comment]
* 의도가 명확한 이름을 지어라. a, b, c 같은 이름이 아닌 무슨 역할을 하는지 드러내는 이름을 사용해라.
* 그릇된 정보를 피해라. 잘못 이해할 수 있거나 다른 이름과 헷갈리는 이름을 피해라.
* 의미 있게 구분하라. 이름끼리 서로 헷갈리지 않도록 명확히 구분하라.
* 발음하기 쉬운 이름을 사용하라. 프로그래머끼리 소통할 필요가 있다.
* 검색하기 쉬운 이름을 사용하라. 상수값을 그대로 쓰는 등의 행동을 피해라.
* 인코딩을 피해라. 
* 다른 사람도 기억하기 쉬운 이름을 지어라.
* 기발한 이름을 사용하지 마라. 사전 지식 없이도 이해할 수 있는 이름을 지어라.
* 한 개념에는 한 단어를 쓰라. 같은 역할을 한다면 같은 이름을 지어라.
* 말장난을 하지 말라. 서로 다른 역할을 한다면 이름도 다르게 지어라.
* 해법 영역에서 이름을 가져와라. 프로그래머에게 익숙한 개념으로 이름을 지어라.
* 문제 영역에서 이름을 가져와라. 적절한 프로그래밍 용어가 없거나 문제와 직접 연관되어 있다면 해당 영역의 언어를 사용하라.
* 의미 있는 맥락을 추가하라. 같은 맥락의 변수는 같은 접두어를 붙이거나 같은 클래스로 묶어라.
* 불필요한 맥락을 제거하라. 특정 클래스의 멤버라는 사실이 명백하다면 굳이 이름에 덧붙일 필요가 없다.

## 내 생각
다른 사람이 짠 코드를 읽을 때 가장 오랜 시간을 쓰게 되는 과정이 '이 변수/함수가 무슨 일을 할까?'인 것 같다. 여기서 제시된 규칙을 따라서 이름을 짓는다면 좀 더 빠르게 해당 과정을 수행할 수 있을 것이다. 이름을 이해할 수 없다면 코드가 아무리 간결하더라도 이해할 수 없는 나열일 뿐이다.

**Comment by Roddyd94** [comment]
## 필요성
명확한 의도 및 맥락 파악, 개념 구분
쉽고 빠른 의사 소통 및 코드 파악

## 방법
개념
>`널리 쓰이는 의미가 있는 단어` 사용 회피
흡사한 이름 사용 회피
유사 개념에 대해 유사한 표기
다른 개념에 같은 이름 사용 회피
한 개념에 한 단어 사용

맥락
>다른 목적(맥락)에 한 단어 사용 금지
해법/문제 영역에서 이름 차용
클래스/접두어를 통한 맥락 추가
불필요한 맥락 제거

의미
>오보성 이름, 정보 없는 이름 회피
연속된 숫자, 불용어 사용 회피
인코딩 표기 회피, 구현 클래스에 한정 사용
방언(농담)성 이름 사용 자제
발음하기 쉬운 이름 사용
작은 루프 범위에서 한 글자 사용 ok

형태
>클래스, 객체 이름은 명사(구) 사용
메서드 이름은 동사(구) 사용
접근자(get)/변경자(set)/조건자(is) 표준

## 생각
결국은 개념을 잘 알고 의미와 맥락을 잘 전달하기 위함으로 보인다.
그리고 프로그래머라면 이 정도 개념은 알아야지 하고 저자가 넘겨 짚는 부분도 있는 것 같다.
이 명명법에 완전히 통달하려면 전문가 정도의 개념 지식과 프로그래밍 역사에 대한 이해가 필요할 듯.
