### ISSUE TITLE
[3장] 함수

### ISSUE THREAD

**Issue by aronalee** [aronalee/swm_14_div_study#4]

**Comment by aronalee** [comment]
# 정리

> 함수는 한가지의 일만 해야한다

- 함수 코드를 읽다가 주춤하는 일이 발생한다면 클린하지 않는 코드라는 의미이다
- 함수를 읽다가 함수의 정의부분을 찾아 읽는 행위는 함수 코드를 읽다가 주춤하는 행위랑 동급이다 
- switch문을 이용할 때는 상속을 통해 switch문을 로직 코드에서 분리를 시켜라
- 함수코드를 읽으면서 머릿속으로 생각한 내용 그대로 수행하는 과정이 떠오르면 좋은 함수명이다.
   - 이름이 길어지는 것을 두려워하지 말아라
- 함수의 인수는 많으면 많을수록 함수를 이해하기 어려워지기에 최대한 적게 사용해라(최대 3개)
- 함수는 동사, 인수는 명사로 쌍을 이뤄야 함수의 의도를 쉽게 표현할 수 있다.
- 에러 코드의 처리는 함수르 호출한 호출자가 직접 처리해야 하므로 비추한다
   - try-catch를 로직에서 분리시켜 에러 처리 기능과 로직 기능을 분리시켜라
   - 에러 처리도 하나의 기능이다
   - 에러코드를 관리하는 객체도 하나의 의존성 자식이다.
> 함수는 한가지의 일만 하라는 원칙을 지키지 못하면 읽기 어려워지고 사이드 이팩트가 발생할 가능성이 높아진다.

---

# 생각

에러 코드를 지양하라는 것은 예전에 자주하던 실수여서 기억이 난다. 과거에도 이걸 쓰면서 '문제가 있는건 알겠는데 이걸 어떻게 풀지' 라는 고민을 하였다. 이때 정확히 어떤 문제였는지 정의하지 못했는데 당시를 회상해보니 '에러코드를 관리하는 객체도 하나의 의존성 자식'이라서 새로운 에러 코드가 추가, 기존 에러코드 수정이 어려웠기 때문이었다는 것을 깨달았다.

**Comment by Roddyd94** [comment]
## 필요성
읽고 이해하기 쉬운 함수 작성
중복 제거

## 방법
작게 만들기
>제어문 블록/중첩 구조 없애기
추상화 수준에서 한 가지만 하는 함수 작성
switch 문을 저차원 클래스에 숨기기

함수 이름과 역할
>서술적인 이름 사용
명령과 조회 분리
이벤트 등 함수 형식이 드러나는 이름
인수의 순서와 의도를 알 수 있는 이름
함수 이름에 temporal coupling이나 order dependency 명시

함수 인수
>인수 개수 줄이기
출력 인수 지양
플래그 인수 지양
여러 인수를 개념으로 묶기
가변 인수를 List형 인수 하나로 취급하여 상기 원칙 적용

오류
>오류 코드 지양
오류 처리 함수로 분리

## 생각
함수를 줄이는 과정을 보면서 인지 과학에서 설명하는 단기 기억의 개념이 떠올랐다.
함수를 작성하는 쪽은 장시간 동안 함수를 충분히 시연한다.
따라서 장기 기억에 역할이나 의도와 맥락 등 함수 각 부분의 정보가 머릿속에 남을 것이다.
하지만 코드를 읽는 사람은 단기 기억을 사용하며 이해해야 하는 경우가 많을 것이다.
그리고 인간의 단기 기억 용량은 평균 3~4개 이다.
그러므로 코드를 읽을 사람을 고려한다면 함수 내에 들어갈 추상화 개념 수가 최대한 적어야 한다는 것에 동의한다.

다만 함수 개수가 늘어나면 외워야 할 이름이 많아진다.
이름을 정말 잘 지어야겠다.

**Comment by chj990707** [comment]
함수는 작게 만들어라
한 가지 일만 하게 하라
함수 내의 추상화 수준을 일관적으로 유지하라
switch-case 문은 최소한으로 한다
이름에 무슨 일을 하는지 드러나게 하라
함수 인수
> 함수 인수를 최소한으로 유지하라
> 플래그 인수는 함수가 여러 일을 하고 있다는 뜻이다
> 서로 관련된 인수 여러 개가 있다면 하나의 자료형으로 묶어라
> 부수적인 효과를 일으키지 마라
> 출력 인수는 피하라

명령과 조회를 분리해라(한 번에 한 가지 일만)
오류를 반환하기보다는 예외를 발생시켜라
> 예외 처리 함수도 다른 일을 시키지 마라

똑같은 코드를 여러 번 반복하지 마라

## 생각
함수는 모든 일을 처리하는 도구인 만큼 이해하기 쉬워야 한다. 물론 앞 장에서 말한 대로 이름을 잘 짓는 것 역시 중요하지만 아무리 이름을 잘 지었어도 복잡하게 섞여 있다면 이름이 아무리 명확해도 허튼소리처럼 보이는 코드가 된다. 추상화 레벨을 똑같이 유지하면서 함수를 짧게 유지하라는 원칙은 코드를 책의 목차를 쓰듯이 짜라는 뜻으로 이해할 수 있다. 이 원칙을 지킨다면 책의 목차를 보고 내용을 파악할 수 있는 것처럼 이해하기 쉬운 코드가 나올 것이다.
