### ISSUE TITLE
[4장] 주석

### ISSUE THREAD

**Issue by aronalee** [aronalee/swm_14_div_study#5]

**Comment by aronalee** [comment]
# 요약

> 주석으로 표현하는 방법은 지양해야 한다.
- 주석까지 유지보수하는 것은 현실적으로 불가능하다. 그렇기에 주석을 없애는 방향으로 힘을 써라
- 주석을 유의미하게 쓰는 경우
   - 법적인 효력이 있는 주석(Copyright)
   - 정보를 제공하는 주석(regex 패턴 예시)
   - 의도를 설명하는 주석(왜 이 로직으로 작성하였는가)
   - 의미를 명료하게 밝힌 주석(명확한 수식, 패턴으로 의미를 명료하게 표현)
   - 결과를 경고하는 주석(과거에 TC의 경우 이를 실행하면 시간이 오래걸린다는 표현으로 사용. 현재는 @Ignore같은 코드레벨로 표현할 수 있는 방법들이 존재)
   - TODO 주석(앞으로 뭘 할 것인지를 남겨놓음)
- 나쁜 주석
   - 무의미한 정보까지 나열한 주석(에라토스테네스의 체에서 에라토스테네스가 누구인가)
   - 이해가 안되어 다른 코드를 읽어야 하는 주석
   - 의무감에 채우거나 같은 이야기를 중복으로 하거나 있으나 마나한 주석(무의미한 말들이 남발하게 되어 다른 의미있는 주석까지 무시하게 된다)
   - 주석으로 처리한 코드(이후 인계받는 개발자가 이를 지우기를 꺼려한다. 중요한 코드일 수도 있기 때문이다)
   - 전역 정보를 표현하는 주석(전역값이 바뀌면 주석도 같이 바꿔줘야 하는데 주석을 유지보수하긴 어려우므로 정보를 혼용될 수 있다)
---

# 내 생각

이번 내용은 주석에 대해 많은 생각을 하게 한다.
TODO주석은 로컬에서 깃쓸 때 자주 사용하곤한다. 이걸 이슈나 브랜치에 올리기엔 애매한 경우에는 TODO로 주석남겨놓고 내일 작업을 처리하곤 한다. 이 습관은 의미있는 주석을 다는 습관이라 유지하되 너무 남용하진 않도록 주의해야하겠다는 생각을 하였다. 
사례중에 JavaDocs를 의무적으로 적는 사례가 나오는 코드를 보고 놀랐다. 주석을 의무적으로 달게하면 이런 문제가 발생할 수 있다는 것을 알 수 있었기 때문이다. jetbrains계열의 document기능을 이용하기 위해 javadocs를 많이 쓸려했는데 이 예시를 보니 javadocs보다 책에서 강조하는 것 처럼 주석을 없애는 방향으로 힘을 쓰는 것이 더 효율적이라는 생각을 하게 되었다.

**Comment by Roddyd94** [comment]
주석 쓰지 마라

## 주석을 사용하는 경우
`써야 하는 경우 or 쓰면 좋은 경우로 생각된다.`
> 저작권, 소유권 등 법적인 주석
공개 API의 JavaDocs
경고 및 중요성 강조
의도 표현
정보 제공 및 의미 명료화 목적
TODO

그 외 -> 사용하지 말 것

## 생각
주석을 써야 하는 경우 외에는 주석을 사용하지 말라는 의도로 보인다.
(쓰면 좋은 경우에도 쓰지 말라는 것 같다.)

다만 초보자가 자신이 쓴 코드에 주석이 필요 없다고 착각하는 순간 문제가 생길 수도 있을 것 같다.
(자신이 붙인 이름이 명료하고 모든 정보를 포함할 수 있다고 확신할만한 근거는?)

1. 제일 좋은 것은 이름을 보고 모든 것을 파악하는 것이고
2. 그 다음은 이름을 보고 이해를 못했을 때 주석을 보는 순간 이해하는 것이고
3. 최악은 주석을 보고도 이해를 못하는 것이 될 것 같다.

2번에서 주석이 없어서 함수 이름을 몇 번 보고 결국 함수 내부를 들여다보게 되면 주석을 쓰는 게 나을 것 같다.
