### ISSUE TITLE
[5장] 형식 맞추기

### ISSUE THREAD

**Issue by aronalee** [aronalee/swm_14_div_study#6]

**Comment by aronalee** [comment]
## 요약

> 코드를 신문기사 쓰듯이 써라

- 일반적으로 코드는 위 ->아래 순으로 코드를 읽는다.
- 개념적 유사성이 높은 순으로 작성해라
   - 개념적으로 비슷한 유형끼리 묶어야 한다
   - 연산식이면 연산자 우선순위, 함수면 호출 순서로 작성할 것을 권장
- 개념적으로 묶는 방법
   - 행: 공백으로 묶어라. 예를 들어 연산식이면 연산자 우선순위로 공백을 채워라
   - 열: 함수는 위에는 중요한 내용, 점점 아래로 갈 수록 세부적인 내용들을 넣느다. 즉 위에는 중요한 내용을 동작하는 과정에 대한 설명, 내부적으론 이 동작을 어떻게 구현하는지로 써라
- 위의 모든 규칙은 팀 룰보다 우선될 순 없다.

---

## 생각

연산자 우선순위를 공백으로 표현하는 방법은 신기했다. 기존에 ide 코드 포맷팅을 사용하다보니 연산자 우선순위를 공백으로 표현하는 건 신기했다. 우선순위로 바뀐 것을 보니 읽기가 더 쉬워졌다. 이 방법은 연산자를 사용할 때면 써보고 싶다는 생각을 하였다.

**Comment by Roddyd94** [comment]
## 필요성
역시나 가독성

## 방법
행 길이 맞추기
>약 200줄의 파일 길이로도 대규모 시스템 구축 가능
빈 행: 개념 단위 분리 및 유사 개념 밀집
수직 거리: 연관성 높은 개념 클러스터링
> - 변수: 사용하는 위치에 근접한 위치
> - 로컬 변수: 각 함수 시작 부분(함수가 짧기 때문)
> - 루프 제어 변수: 루프문 내부
> - 인스턴스 변수: 언어에 따라 클래스 시작/마지막 부분
> - 종속 함수: 가능한 자신이 호출된 함수 아래
>
>개념 친화도: 높을수록 가까이 배치

열 길이 맞추기
>가로 공백: 개념(연산자, 함수, 인수) 구분
가로 정렬: deprecated
들여쓰기: 범위 계층 표현
빈 반복문: 아래 행에 세미콜론

**팀 규칙 따르기**


## 생각
형식이래서 전체적인 코딩 컨벤션을 떠올렸는데 모양새에 관한 이야기였다. 모양새는 알게 모르게 적용하던 내용이라 신기했다.
파일의 크기와 파일의 개수는 역함수 관계이므로 둘을 적당히 고려해야 한다고 생각했었다. 하지만 파일 하나가 신문 기사 하나라는 비유를 통해 파일의 개수가 늘어나더라도 파일 개수는 색인에 맡기고 파일의 크기를 적당히 작게 유지하는 것이 좋겠다는 생각을 했다.
팀 규칙을 예시로 때워 아쉬웠다.

**Comment by chj990707** [comment]
* 코드 전체 길이를 짧게 유지해라
* 개념을 공백 줄로 분리해라
* 서로 연관된 개념은 수직으로 가까운 거리에 배치하라
> 변수는 사용하는 위치와 근접한 곳에 배치하라
> 함수 본문은 호출로 인한 종속성이 발생한 곳 아래에 배치하라

## 생각
다른 사람이 짠 코드를 분석할 때 대부분의 조작이 함수나 변수의 선언/용례를 찾기였던 것 같다. 이 장에서 제시된 규칙을 따르면 수고를 확실히 줄일 수 있을 것이다. 더해서, 파일의 길이를 짧게 유지하는 규칙도 개별 파일을 읽는 데에는 크게 도움이 되지만 실제로 코드를 짤 때는 기능이 하나씩 추가되는 일이 많아 자주 상기해야 할 것이다.
