### ISSUE TITLE
[6장] 객체와 자료구조

### ISSUE THREAD

**Issue by aronalee** [aronalee/swm_14_div_study#7]

**Comment by aronalee** [comment]
# 요약

- 객체지향은 함수를 수정하는 것이 어렵다. 이 함수와 상속, 추상화등 관련된 모든 객체를 바꿔야하기 때문이다. 그러나 자료구조를 추가하기에는 용이하다. 
- 절차지향은 함수를 수정하기 용이하다.  그러나 자료구조를 추가하기 어렵다.
- 객체지향에서 어려운 것은 절차지향에서는 쉬워지고 반대도 마찬가지이다.
- 모든 것은 객체로 만들 수 없다. 상황에 따라 객체지향, 절차지향을 선택해서 만들어야 한다
- 디미터 법칙: 자신이 조작하는 객체의 내부구조를 알 필요가 없다.
- 객체는 자료를 숨기고 동작을 공개한다.

---

# 생각

객체지향은 만능이 아니라는 것을 알려주려는 내용으로 생각했다. 특히 '모든 것은 객체로 만들 수 없다' 는 java의 사상과 완전히 반대되는 내용이라 공감이 된다.

**Comment by chj990707** [comment]
* 객체지향에서는 새로운 자료를 추가하기는 쉽지만, 함수를 추가하기는 어렵다.
* 절차지향에서는 반대로 함수를 추가하기는 쉽지만 새로운 자료형을 추가하기는 어렵다.
* 상황에 따라 객체와 단순 자료를 구분해서 쓰자.
* 디미터 법칙 - 자신이 조작하는 객체의 속사정을 알 필요가 없다.

### 생각
모든 것을 객체로 만들 수는 없다는 내용이 이론적으로는 이해가 가지만 관성적으로 객체로 만드는 습관 때문에 실제로 적용하기 어려울 것 같다는 생각이 들었다.

**Comment by Roddyd94** [comment]
## 자료 표현 방법
객체
- 추상화
- 자료 은닉
- 자료를 다루는 함수만 공개
- 새로운 자료 타입이 필요한 경우 적합

자료 구조
- 자료 공개
- 함수 미제공
- 새로운 함수가 필요한 경우 적합

디미터 법칙
- 내부 구조를 공개하는 조회 함수 금지
- 기차 충돌 지양: 자료 구조인 경우에만 조회 함수 없이 사용
- 적당한 임무 부여: 자신이 알 필요 없는 객체를 탐색하지 않도록

자료 전달 객체(DTO)
- 함수 없이 공개 변수만 존재하는 클래스
- 활성 레코드: DTO + save/find 등 탐색 함수 제공, 기타 메서드 추가 지양

## 요점
자료를 숨기고 접근 방법을 강제, 자료의 변경 -> 객체
함수의 변경 -> 자료 구조

## 생각
C++에서 struct와 class가 같은 방식으로 사용할 수 있고 default access가 public이냐 private이냐의 차이만 있는 이유를 알게 되었다! struct는 (말 그대로) 자료구조니까 (자료에 대해) public인 것이고, class는 객체니까 (자료에 대해) private인 것이다.
클래스 외부에 함수가 없는 자바는 자료 구조를 다루기 위한 함수를 어떻게 정의하는지가 궁금해졌다.
