### ISSUE TITLE
[8장] 경계

### ISSUE THREAD

**Issue by aronalee** [aronalee/swm_14_div_study#9]

**Comment by Roddyd94** [comment]
## 방법
> 외부 코드 사용
>- 외부 코드 캡슐화
>- 클래스 내 경계 인터페이스의 외부 노출 금지
>- 외부 코드 학습 테스트
>
> 미구현 외부 코드 사용
>- 자체 인터페이스 정의
>- Controller 분리
>- Adapter 적용
>- Fake 구현체 사용 테스트

## 요점
외부 API 직접 호출 지양

## 생각
외부 API를 사용하다가 골머리를 앓은 적이 많아 많은 공감이 되었다. 학습 테스트를 통해 외부 API 사용법을 배우고, 래핑 클래스나 자체 인터페이스 정의를 통해 입맛에 맞게 사용하면서도 외부 API 호출을 줄인다는 개념을 처음 접했다. 기능 구현에만 집중하다 보니 인터페이스 사용이나 래핑 클래스 같은 사용법이 있는 줄도 몰랐다. 많이 공부하고 연구해야겠다는 생각이 들었다.

**Comment by aronalee** [comment]
# 요약

- 경게를 지키면 의도치 않는 동작을 방지할 수 있다
- 경계를 지키면 테스트를 용이하게 할 수 있다
- 경계를 지키면 연계된 서비스가 준비가 안되어있다하더라도 독자적으로 서비스를 구축할 수 있다
- 경계를 지키기 위해서는 외부에 공개되어서는 안되는 자료구조를 숨겨라
   - 예시: java의 Map 객체는 누구나 clear를 통해 데이터를 초기화시킬 수 있기에 직접 접근을 막아야 한다
- 학습테스트를 이용하면 외부 서비스 학습을 할 수 있다.
   -  학습테스트: 모르는 기능을 알기 위해 간단한 테스트를 짜보면서 기능을 이해하는 방법
- 외부 서비스와 연동할 경우 인터페이스를 통해 경계를 만들면 서비스가 만들어지기 전까지 테스트를 만들 수 있다.

---

# 생각

Collection 자료구조를 쓰면서 누구나 clear를 호출할 수 있다는 생각을 못해봤다. Collection 객체를 이용할 때는 '누구나 이 값을 삭제할 수 있겠구나' 라는 점을 염두하면서 작성해야한다는 생각을 하여 시야가 넓어진 느낌이 들었다.

**Comment by chj990707** [comment]
경계 인터페이스를 외부에 노출시키지 말라
연결된 서비스가 아직 준비되지 않았어도 경계를 잘 지키면 코드를 구축할 수 있다
외부 패키지를 호출하는 코드를 최대한 줄여 코드를 깨끗하게 유지하라

### 생각
아직 존재하지 않는 코드와 호환되는 코드를 짜는 방법을 제시해서 놀라웠다. 본문에서 제시한 가짜 클래스는 추후에 파사드 패턴처럼 사용할 수도 있을 것 같다는 생각이 들었다.
